name: C++ Tests and Coverage

on:
  push:
    paths:
      - 'projects/cPlusPlus/**'
  pull_request:
    paths:
      - 'projects/cPlusPlus/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - { cc: gcc-11, cxx: g++-11 }
          - { cc: gcc-12, cxx: g++-12 }
          - { cc: gcc-13, cxx: g++-13 }
          - { cc: clang-15, cxx: clang++-15 }
          - { cc: clang-16, cxx: clang++-16 }
          - { cc: clang-17, cxx: clang++-17 }
      fail-fast: false  # Continue testing other configurations even if one fails

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lcov gcovr cmake
          # Install specific compiler versions
          sudo apt-get install -y ${{ matrix.compiler.cc }} ${{ matrix.compiler.cxx }}

      - name: Configure CMake
        env:
          CC: ${{ matrix.compiler.cc }}
          CXX: ${{ matrix.compiler.cxx }}
        run: |
          cd projects/cPlusPlus
          cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="--coverage"

      - name: Build
        env:
          CC: ${{ matrix.compiler.cc }}
          CXX: ${{ matrix.compiler.cxx }}
        run: |
          cd projects/cPlusPlus
          cmake --build build

      - name: Run tests
        run: |
          cd projects/cPlusPlus/build
          ctest --output-on-failure

      - name: Generate and show detailed coverage in console
        run: |
          cd projects/cPlusPlus/build
          gcovr -r .. --exclude '.*gtest.*' --exclude '.*nlohmann.*' --txt