name: c++ Tests and Coverage

on:
  push:
    paths:
  #      - 'projects/cPlusPlus/**'
  pull_request:
    paths:
#      - 'projects/cPlusPlus/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc-10, gcc-11, clang-11, clang-12]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y lcov gcovr cmake g++ clang

      - name: Set up compiler
        run: |
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/${{ matrix.compiler }} 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/${{ matrix.compiler }} 100
          sudo update-alternatives --set gcc /usr/bin/${{ matrix.compiler }}
          sudo update-alternatives --set g++ /usr/bin/${{ matrix.compiler }}

      - name: Configure CMake
        run: |
          cd projects/cPlusPlus
          cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="--coverage"

      - name: Build
        run: |
          cd projects/cPlusPlus
          cmake --build build

      - name: Run tests
        run: |
          cd projects/cPlusPlus/build
          ctest --output-on-failure

      - name: Generate and show detailed coverage in console
        run: |
          cd projects/cPlusPlus/build
          gcovr -r .. --exclude '.*gtest.*' --exclude '.*nlohmann.*' --txt
