name: Java Tests

on:
  push:
    paths:
      - 'projects/java/**'
  pull_request:
    paths:
      - 'projects/java/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 8, 11, 17 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          cache: 'maven'

      - name: Run tests with coverage
        run: |
          cd projects/java
          mvn clean verify

      - name: Create JAR
        run: |
          cd projects/java
          mvn clean package