name: Kotlin Tests

on:
  push:
      paths:
        - 'projects/kotlin/**'
  pull_request:
    paths:
      - 'projects/kotlin/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ '17', '21' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          cache: 'gradle'

      - name: Build project
        run: |
          cd projects/kotlin
          ./gradlew build

      - name: Run tests with coverage
        run: |
          cd projects/kotlin
          ./gradlew test jacocoTestReport --console=plain

      - name: Show test results in console
        run: |
          cat projects/kotlin/build/test-results/test/TEST-*.xml || true

      - name: Show coverage summary in console
        run: |
          cd projects/kotlin
          ./gradlew jacocoTestCoverageVerification --console=plain || true

      - name: Create JAR
        run: |
          cd projects/kotlin
          ./gradlew jar