name: Kotlin Tests

on:
  push:
  #    paths:
  #      - 'projects/python/**'
  pull_request:
#    paths:
#      - 'projects/python/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ '17', '21' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          cache: 'gradle'

      - name: Build project
        run: |
          cd projects/kotlin
          ./gradlew build

      - name: Run tests with coverage
        run: |
          cd projects/kotlin
          ./gradlew test jacocoTestReport

      - name: Show test results
        run: |
          cat projects/kotlin/build/reports/tests/test/index.html || true  # Покажем результаты тестов

      - name: Show coverage report
        run: |
          cat projects/kotlin/build/reports/jacoco/test/html/index.html || true  # Покажем покрытие кода

      - name: Create JAR
        run: |
          cd projects/kotlin
          ./gradlew jar